Conco/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name = 'signup'),
    path('accounts/login/done/', views.RegisteredView.as_view(), name = 'create_user_done'),
]

board/urls.py
from board import views
from django.urls import path, re_path



app_name = 'board'

urlpatterns = [
    path('board/', views.index.as_view(), name='index'),
    path('board/new/', views.new_post, name='new_post'),
    re_path(r'^board/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    re_path(r'^board/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    re_path(r'^board/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    re_path(r'^board/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
]

board/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

def min_length_3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('제목을 3글자 이상 입력해주세요.')

def min_length_10_validator(value):
    if len(value) < 10:
        raise forms.ValidationError('내용을 10글자 이상 입력해주세요.')

class Post(models.Model):
    title = models.CharField(max_length=30, validators=[min_length_3_validator])
    text = models.TextField(validators=[min_length_10_validator])
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    regdate = models.DateTimeField(auto_created=True, auto_now_add=True)

    def generate(self):
        self.save()

    def __str__(self):
        return '%s by %s'%(self.title, self.author)


class Comment(models.Model):
    post = models.ForeignKey('board.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

board/forms.py
from django import forms
from board.models import Post, Comment

from django.contrib.auth import get_user_model

User = get_user_model()

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': '제목은 3자 이상 입력해주세요.'})
        self.fields['text'].widget.attrs.update({'class': 'form-control', 'placeholder': '내용은 10자 이상 입력해주세요.'})

    class Meta:
        model = Post
        fields = ('title', 'text',)




class SignupForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    password = forms.RegexField(regex=r'^(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]|.*[0-9]).{8,24}$', widget=forms.PasswordInput(attrs={'class': 'form-control',}))
    password_confirm = forms.RegexField(regex=r'^(?=.*[a-zA-Z])(?=.*[^a-zA-Z0-9]|.*[0-9]).{8,24}$', widget=forms.PasswordInput(attrs={'class': 'form-control',}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('아이디가 이미 사용중입니다.')
        return username

    def clean_password_confirm(self):
        password1 = self.cleaned_data['password']
        password2 = self.cleaned_data['password_confirm']
        if password1 != password2:
            raise forms.ValidationError('비밀번호가 일치하지 않습니다.')
        return password2

    def signup(self):
        if self.is_valid():
            return User.objects.create_user(
                username = self.cleaned_data['username'],
                password = self.cleaned_data['password_confirm'],
            )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from board.models import Post, Comment
from board.forms import PostForm, SignupForm, CommentForm
from django.http import HttpResponse
from django.contrib.auth.models import User

from django.views.generic import TemplateView, ListView

from django.utils import timezone

from django.contrib.auth.decorators import login_required
# Create your views here.



# ListView로 게시물 리스트 구현
class index(ListView):
    model = Post
    paginate_by = 10
    def get_queryset(self):
        return Post.objects.order_by('-pk')

# 게시물 내용
def post_detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    context = {
        'post_detail': post_detail,
    }
    return render(request, 'board/post_detail.html', context)


# 새 글 작성
@login_required
def new_post(request):
    if request.method =="POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit = False)
            post.author = request.user
            post.generate()
            return redirect('board:post_detail', pk=post.pk)
    else:
            form = PostForm()
    return render(request, 'board/form.html', {'form': form})

# 글 수정
@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == User.objects.get(username=request.user.get_username()):
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.regdate = timezone.now()
                post.generate()
                return redirect('board:post_detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
        return render(request, 'board/form.html', {'form': form})
    else:
        return render(request, 'board/warning.html')

# 글 삭제
@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == User.objects.get(username = request.user.get_username()):
        post.delete()
        return redirect('board:index')
    else:
        return render(request, 'board/warning.html')


# 회원가입
def signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)
        if signup_form.is_valid():
            signup_form.signup()
            return redirect('board:index')
    else:
        signup_form = SignupForm()

    return render(request, 'registration/signup.html', {'signup_form': signup_form,})

# TemplateView로 회원가입 완료 페이지 구현
class RegisteredView(TemplateView):
    template_name = 'registration/signup_done.html'


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'board/add_comment_to_post.html', {'form': form})

board/templates/board/add_comment_to_post.html
{% extends 'board/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="post" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-dark">Send</button>
    </form>


{% endblock %}

board/templates/board/base.html
<!DOCTYPE html>
<html lang="ko" xmlns:margin-left="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Conco Freeboard</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="/static/css/board.css" />

    <!-- Font Awesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>

    <!-- CSS -->
    <style>
        #button_align {
            width: 400px;
            margin-left: 63%;
            text-align: right;
        }
        .comment {
            margin: 20px 0px 20px 20px;
            background-color: whitesmoke;
        }
    </style>

</head>
<body>
    <div class="container">

        {% load static %}
        <a href="{% url 'board:index' %}">
            <img src="{% static "img/logo1.png" %}" width="400px" height="100px" >
        </a>


        <nav class="navbar navbar-light navbar-expand-md sticky-top" style="background-color: #e3f2fd;">

            {% if user.is_active %}
                <a class="navbar-brand" href="{% url 'login' %}"><i class="fas fa-user"></i> {{ user.username }}님!</a>
            {% endif %}
            CONCO KOREA 게시판에 오신 것을 환영합니다.

            <ul class="navbar nav mr-auto"></ul>

            <ul class="nav nav-pills">
                {% if user.is_active %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}"> Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}"> Login</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>



    <div class="container">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

board/templates/board/form.html
{% extends "board/base.html" %}

    {% block content %}

        <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}

                <div class="form-group">
                    <label>제목</label>
                    {{ form.title }}


                    <div class="invalid-feedback">
                        제목은 3자 이상 입력해주세요.
                    </div>
                </div>



                <div class="form-group">
                    <label>내용</label>
                    {{ form.text }}

                    <div class="invalid-feedback">
                        내용은 10자 이상 입력해주세요.
                    </div>
                </div>

            {% if form.errors %}
                <div class="alert alert-error">
                  <h4>양식에 맞게 글을 작성해주세요</h4>
                  <ul>
                    {% for field in form %}
                      {% if field.errors %}
                        {% for error in field.errors %}
                          <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                        {% endfor %}
                      {% endif %}
                    {% endfor %}
                  </ul>
                  {% if form.non_field_errors %}
                    {{ form.non_field_errors }}
                  {% endif %}
                </div>
              {% endif %}



            <!-- 글쓰기 버튼 -->
            <button type="submit" class="save btn btn-default" data-toggle="modal" data-target="#exampleModal">글쓰기</button>
        </form>



<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
    {% endblock %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}

{% block content %}
    <br>

    <div>


        <table class="table">
          <thead class="thead-light" style="border-left: 1px solid lightgray; border-right: 1px solid lightgray;">
            <tr>
                <th scope="col"><h4>{{ post_detail.title }}</h4></th>
            </tr>
          </thead>
          <tbody style="border-left: 4px solid gold;
                        border-right: 1px solid lightgray;
                        border-bottom: 1px solid lightgray;">
            <tr>
              <td>
                  <p align="right">작성자: {{ post_detail.author }}</p>
                  <p align="right" style="font-size: 13px;">작성일: {{ post_detail.regdate }}</p>
                  <p>{{ post_detail.text|linebreaksbr }}</p>
              </td>
            </tr>
          </tbody>
        </table>


    <!-- 글 수정, 삭제 버튼 -->
        <div id="button_align">
            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary" href="{% url 'board:post_edit' pk=post_detail.pk %}"><i class="fas fa-edit"></i> 수정하기</a>
                <a class="btn btn-outline-danger" href="{% url 'board:post_remove' pk=post_detail.pk %}" onclick="return confirm('정말 삭제하시겠습니까?')"><i class="fas fa-eraser"></i> 글삭제</a>
            {% endif %}
        <!-- 목록 버튼 -->
                <a class="btn btn-outline-secondary" href="{% url 'board:index' %}"><i class="fas fa-list-ul"></i> 목록으로</a>
        </div>
    </div>

    <hr>
    <a class="btn btn-primary" href="{% url 'board:add_comment_to_post' pk=post_detail.pk %}">Add comment</a>
    {% for comment in post_detail.comments.all %}
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}

<script>
    $("#user_name").text()
</script>


{% endblock %}

board/templates/board/post_list.html
{% extends 'board/base.html' %}

    {% block content %}
    <br>
        <div class="" style="border: 2px outset #c4dce8;">

            <table class="table table-striped table-hover">
                <colgroup>
                    <col span="1" width="12%">
                    <col span="1" width="50%">
                    <col span="1" width="18%">
                    <col span="1" width="20%">
                </colgroup>

                <thead>
                    <tr>
                        <th>글번호</th>
                        <th>제목</th>
                        <th>작성자</th>
                        <th>등록일</th>
                    </tr>
                </thead>

                <tbody>
                {% for post in post_list %}
                    <tr>
                        <td>{{ post.pk }}</td>
                        <td><a href="{{ post.pk }}">{{ post.title }} <small style="color: darkorange">[{{ post.comments.count }}]</small></a></td>
                        <td>{{ post.author }}</td>
                        <td>{{ post.regdate }}</td>
                    </tr>
                 {% endfor %}
                </tbody>
            </table>

        </div>

        <br>

        <!-- 페이징 -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }}<span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
        </nav>
        {% endif %}

        <!-- 글쓰기 버튼 -->
        <div class="" style="width: 100px; float: right;">
        <a href="{% url 'board:new_post' %}" class="btn btn-dark btn-sm" role="button"><i class="fas fa-pencil-alt"></i> 글쓰기</a>
        </div>


    {% endblock %}

board/templates/board/warning.html
{% extends 'board/base.html' %}

{% block content %}

    <p>본인이 작성한 글이 아니면 수정하거나 삭제할 수 없습니다.</p>

{% endblock %}